### ISSUE TITLE
issue with 

### ISSUE THREAD

**Issue by waadaa85** [onethawt/idapyscripts#1]
Hello,

I got the following error when I tried the script:
IDAPython: Error while calling Python callback <OnCreate>:
Traceback (most recent call last):
  File "D:/IDA695/scripts/dataxrefcounter.py", line 58, in OnCreate
    self.parent = self.FormToPySideWidget(form)
  File "D:\IDA695\python\ida_kernwin.py", line 5673, in FormToPySideWidget
    return ctx.QtGui.QWidget.FromCObject(form)
AttributeError: type object 'PySide.QtGui.QWidget' has no attribute 'FromCObject'

PySide is version 1.2.1 (provided by Anaconda 4.2.12 python 2.7)
Ida Pro is 6.95, windows 32bits

I'd put the script in %IDAHOME% = D:\IDA695

Kind Regards,
Waadaa

**Comment by onethawt** [comment]
I haven't actually used the script for a long time, I'll look into it this week.

**Comment by Triphammer7th** [comment]
Hello,

Any chance this has been resolved? I was trying to use the dataxrefcounter.py plugin but I keep getting this error.

**Comment by onethawt** [comment]
IDA 6.9+ ships with Qt 5+ and no longer supports PySide. I will create a PyQt5 version over the weekend.
